# Generated by Django 2.2.7 on 2019-11-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('V', 'Vegetables'), ('F', 'Fruits'), ('J', 'Juice'), ('D', 'Dried')], default='V', max_length=1),
            preserve_default=False,
        ),
    ]
