# Generated by Django 2.2.7 on 2019-11-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
